support anonymous auth
CloudSoda/go-smb2 pull request #13
Opened 2023-10-20 10:50 UTC by deitch

This PR adds support for anonymous auth, i.e. no provision of username and password. Of course, if the requested share does not allow it, it will return an auth error, which it should. If connecting to a share that allows anonymous access, it will work.

While doing so, I moved the Unmarshaling of the challenge message into its own function and struct. I needed it to make the `Authenticate()` function clearer to read, to figure out why something wasn't working. Once I figured it out, I left it there. If it bothers you, I can put it back to how it was before.

I extended the test `TestClientServer()` in `ntlm_test.go`. However, it appears that `s.Authenticate()` calls the server authentication directly, and our server does not know how to handle anonymous clients. So that is not a great test. I also am not sure how to update the server correctly to do this. Help would be appreciated.

2023-10-20 10:50 UTC, deitch commented
Fixes #10

2023-10-20 14:39 UTC, deitch commented
FYI, I tested it manually against a samba instance

2023-10-25 12:43 UTC, deitch commented
Anything else needed for this, beyond fixing those tests? And any good suggestions how?

2023-10-25 17:24 UTC, arashpayan commented
Hey @deitch. It's just been a very busy time at work. I'll be sure to review the PR this week.

2023-10-30 08:51 UTC, deitch commented
OK, I restructured the server `Authenticate()`, and it handles anonymous correctly now. I checked, it only is used as part of `ntlm_test.go`, and that, in turn, is in `internal/`, so we are covered from all possible use cases. We might want to think about making it public at some point, but that is beyond this PR.

Ready for your review.

2023-11-05 00:00 UTC, arashpayan commented
This looks good @deitch. Just one minor nitpick to address, and then I'll bring it in.

I tested the anonymous authentication against a local Samba server and it worked perfectly. After we merge this in, I'd like to add a test for it to the GitHub workflow.

2023-11-05 05:20 UTC, deitch commented
What nitpick is that? I didn't see any other comment 🤷‍♂️

2023-11-05 20:26 UTC, arashpayan requested changes

2023-11-05 20:26 UTC, arashpayan commented on internal/ntlm/common.go
> +	anonymousKeyExchangeKey = []byte{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
* Could you add a comment explaining/linking where this particular value came from?
* Because it's a single variable, please declare it in one line i.e. `var anonymous... `

2023-11-05 20:26 UTC, arashpayan commented on internal/ntlm/client.go
> +	}
Factoring out the magic numbers into variables made this a lot easier to understand. Thank you!

2023-11-05 20:26 UTC, arashpayan commented
Oops. I forgot to submit the review.

2023-11-06 07:06 UTC, deitch commented on internal/ntlm/common.go
> +	anonymousKeyExchangeKey = []byte{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
Done. I wish I could make it a const, but you cannot have a const slice. Take a look.

2023-11-06 20:59 UTC, arashpayan approved these changes
Looks good.

2023-11-06 20:59 UTC, merged